services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/nextpoke/pokenext
    container_name: ctdavidnextpoke
    image: dsegura97/nextpoke
    ports:
      - 3010:3000
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
