apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.container.name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations: {}
spec:
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.container.name }}-service
            port:
              number: {{ .Values.frontend.ingress.port }}
